##This script takes in data generated by the accelerometers on a Samsung phone,
## gives the data proper names, cleans up the formatting,
## selects out only the columns that are means or standard devs,
## and calculates the averages of those columns per test subject and activity.

library(dplyr)
library(reshape2)

##We begin by reading in the various files in the test and train folders.
features<- read.table("./features.txt", stringsAsFactors=FALSE)
activity_labels <- read.table("./activity_labels.txt", stringsAsFactors=FALSE)
subject_test <- read.table("./test/subject_test.txt")
x_test <- read.table("./test/X_test.txt", col.names=features$V2)
y_test <- read.table("./test/y_test.txt")
subject_train <- read.table("./train/subject_train.txt")
x_train <- read.table("./train/X_train.txt", col.names=features$V2)
y_train <- read.table("./train/y_train.txt")

#Next, we merge the test and training sets together.
#First, subject_test and subject_train will be merged, x_test and x_train will be merged,
# and y_test and y_train will be merged.

#The data will always be merged with test coming before train in order to maintain consistency
# between file types.
subject_total <- rbind(subject_test, subject_train)
x_total <- rbind(x_test, x_train)
y_total <- rbind(y_test, y_train)

#Before merging everything into one big data frame, we should name the columns.  
#The x_train and x_test columns are already named.
y_total <- rename(y_total, activity = V1)
subject_total <- rename(subject_total, subject = V1)


#Next, we combine subject_total, x_total, and y_total into one massive data set.
total <- cbind(subject_total, x_total, y_total)

#Now we select out just the means and stds, as requested.
meansAndStds <- select(total, activity, subject, contains("mean.", ignore.case=FALSE), contains("std.", ignore.case=FALSE))

#Let's make those activity names more verbose and descriptive, and fix the x names.
colnames(meansAndStds) <- gsub("\\.", "", colnames(meansAndStds))
for(i in 1:nrow(meansAndStds)) {meansAndStds$activity[i] <- activity_labels[meansAndStds$activity[i],2]}

#Finally, we melt the data down and calculate the average for each measurement for each subject/activity
meltedMsSs <- melt(meansAndStds, id=c("activity", "subject"))
averages <- dcast(meltedMsSs, activity + subject ~ variable, mean)
write.table(averages, file="./averagesPerActivitySubject.txt", row.name=FALSE)
